/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : Time,
});
export const Conversation = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const ConversationSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'lastUpdated' : Time,
  'messageCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Nat, Role, IDL.Text], [], []),
  'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteConversation' : IDL.Func([IDL.Nat], [], []),
  'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'updateConversationTitle' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : Time,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const ConversationSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'lastUpdated' : Time,
    'messageCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Nat, Role, IDL.Text], [], []),
    'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteConversation' : IDL.Func([IDL.Nat], [], []),
    'getConversation' : IDL.Func([IDL.Nat], [IDL.Opt(Conversation)], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'updateConversationTitle' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };